apiVersion: v2
name: sonda
description: Synthetic telemetry generator for testing observability pipelines
type: application
version: 1.4.0
appVersion: 1.4.0
home: https://github.com/davidban77/sonda
sources:
  - https://github.com/davidban77/sonda
maintainers:
  - name: David Flores
    email: davidflores77@gmail.com
keywords:
  - observability
  - telemetry
  - metrics
  - logs
  - testing
  - synthetic
